--Server: dbsep4768cls
--Dbase: ccs_gim_report
--Global Group to get access: GIM_ENT_Read (no longer used as of 10/12/18).
--Global Group to get access: GIM_ENT_Restricted (limited to US-based employees only)
--Global Group to get access: GIM_ENT_ITL (limited to international employees only)

SELECT
	DATEADD(HOUR, - 5, DATEADD(S, dbo.INTERACTION_RESOURCE_FACT.START_TS, '1970-01-01')) AS 'START_TS (CT)',
	DATEADD(HOUR, - 5, DATEADD(S, dbo.INTERACTION_RESOURCE_FACT.END_TS, '1970-01-01')) AS 'END_TS (CT)',
	dbo.INTERACTION_FACT.INTERACTION_ID AS 'InteractionID',
	dbo.IRF_USER_DATA_CUST_1.CUSTOM_DATA_16 AS 'Cisco-Gucid',
	dbo.INTERACTION_TYPE.INTERACTION_TYPE AS 'InteractionType',
	dbo.MEDIA_TYPE.MEDIA_NAME AS 'MediaName',
	dbo.INTERACTION_RESOURCE_FACT.INTERACTION_RESOURCE_ORDINAL 'IntResOrdinal', 
	dbo.INTERACTION_FACT.SOURCE_ADDRESS AS 'ANI',
    dbo.IRF_USER_DATA_CUST_1.CUSTOM_DATA_1 AS 'email|ANI|chat (ENT_ToAddress)',
	dbo.INTERACTION_FACT.TARGET_ADDRESS AS 'DialedNumber', 
    dbo.IRF_USER_DATA_CUST_2.CUSTOM_DATA_3 AS 'ENT_VQ',
	dbo.TECHNICAL_DESCRIPTOR.TECHNICAL_RESULT AS 'TechResult',
	dbo.TECHNICAL_DESCRIPTOR.RESOURCE_ROLE AS 'ResourceRole',
    dbo.RESOURCE_.RESOURCE_TYPE AS 'ResourceType',
	dbo.RESOURCE_.RESOURCE_NAME AS 'ResourceName',
	dbo.RESOURCE_.AGENT_NAME AS 'AgentName',
	dbo.RESOURCE_.EMPLOYEE_ID AS 'MSID', 
    dbo.IRF_USER_DATA_CUST_2.CUSTOM_DATA_11 AS 'IW_RoutingBasedTargetID',
	dbo.USER_DATA_CUST_DIM_5.DIM_ATTRIBUTE_4 AS 'WWETransferTxt', 
    dbo.USER_DATA_CUST_DIM_5.DIM_ATTRIBUTE_2 AS 'WWEDispositionCD',
	dbo.INTERACTION_DESCRIPTOR.CUSTOMER_SEGMENT AS 'ENT_UnitSegment', 
    dbo.INTERACTION_DESCRIPTOR.SERVICE_TYPE AS 'ENT_Function',
	dbo.INTERACTION_DESCRIPTOR.SERVICE_SUBTYPE AS 'ENT_SubFunction',
	dbo.INTERACTION_DESCRIPTOR.BUSINESS_RESULT AS 'ENT_ContactConstituentType',
	dbo.USER_DATA_CUST_DIM_1.DIM_ATTRIBUTE_1 AS 'StateCode (ENT_ContactStateCD)', 
	dbo.USER_DATA_CUST_DIM_4.DIM_ATTRIBUTE_2 AS 'StateCode (ENT_SubjectStateCD)', 
	dbo.USER_DATA_CUST_DIM_1.DIM_ATTRIBUTE_2 AS 'CallerType (ENT_WFMGroupCD)',
    dbo.USER_DATA_CUST_DIM_1.DIM_ATTRIBUTE_3 AS 'Location (ENT_Location)',
	dbo.USER_DATA_CUST_DIM_1.DIM_ATTRIBUTE_4 AS 'Language (ENT_Language)', 
    dbo.USER_DATA_CUST_DIM_1.DIM_ATTRIBUTE_5 AS 'TransferType (ENT_TransferType)',
	dbo.USER_DATA_CUST_DIM_2.DIM_ATTRIBUTE_1 AS 'IVRProduct (ENT_Product)', 
    dbo.USER_DATA_CUST_DIM_2.DIM_ATTRIBUTE_2 AS 'Client (ENT_Client)',
	dbo.USER_DATA_CUST_DIM_2.DIM_ATTRIBUTE_3 AS 'Unit (ENT_Unit)', 
    dbo.USER_DATA_CUST_DIM_2.DIM_ATTRIBUTE_4 AS 'Segment (ENT_Segment)',
	dbo.USER_DATA_CUST_DIM_2.DIM_ATTRIBUTE_5 AS 'ENT_OrgLvl4', 
    dbo.IRF_USER_DATA_CUST_1.CUSTOM_DATA_3 AS 'ENT_ContactConstituentID',
	dbo.IRF_USER_DATA_CUST_1.CUSTOM_DATA_4 AS 'ENT_ContactGroupID', 
    dbo.IRF_USER_DATA_CUST_1.CUSTOM_DATA_5 AS 'ENT_ContactDOB',
	dbo.IRF_USER_DATA_CUST_1.CUSTOM_DATA_6 AS 'ENT_ContactFirstNm', 
    dbo.IRF_USER_DATA_CUST_1.CUSTOM_DATA_7 AS 'ENT_ContactLastNm',
	dbo.IRF_USER_DATA_CUST_1.CUSTOM_DATA_8 AS 'ENT_ContactZIP', 
    dbo.IRF_USER_DATA_CUST_3.CUSTOM_DATA_6 AS 'ENT_AssignedAgentID',
	dbo.IRF_USER_DATA_CUST_3.CUSTOM_DATA_7 AS 'ENT_CampaignCD', 
    dbo.IRF_USER_DATA_CUST_3.CUSTOM_DATA_8 AS 'ENT_ProgramCD',
	dbo.USER_DATA_CUST_DIM_1.DIM_ATTRIBUTE_1 AS 'ENT_ContactStateCD', 
    dbo.USER_DATA_CUST_DIM_1.DIM_ATTRIBUTE_2 AS 'ENT_WFMGroupCD',
	USER_DATA_CUST_DIM_5_1.DIM_ATTRIBUTE_1 AS 'ENT_SurveyFlag', 
    dbo.IRF_USER_DATA_CUST_2.CUSTOM_DATA_1 AS 'ENT_CallType',
	dbo.INTERACTION_FACT.MEDIA_SERVER_IXN_ID,
	dbo.INTERACTION_FACT.MEDIA_SERVER_IXN_GUID

FROM
	dbo.INTERACTION_RESOURCE_FACT
	INNER JOIN dbo.INTERACTION_FACT ON dbo.INTERACTION_RESOURCE_FACT.INTERACTION_ID = dbo.INTERACTION_FACT.INTERACTION_ID
	INNER JOIN dbo.INTERACTION_TYPE ON dbo.INTERACTION_RESOURCE_FACT.INTERACTION_TYPE_KEY = dbo.INTERACTION_TYPE.INTERACTION_TYPE_KEY
	INNER JOIN dbo.MEDIA_TYPE ON dbo.INTERACTION_RESOURCE_FACT.MEDIA_TYPE_KEY = dbo.MEDIA_TYPE.MEDIA_TYPE_KEY
	INNER JOIN dbo.RESOURCE_ ON dbo.INTERACTION_RESOURCE_FACT.RESOURCE_KEY = dbo.RESOURCE_.RESOURCE_KEY
	INNER JOIN dbo.TECHNICAL_DESCRIPTOR ON dbo.INTERACTION_RESOURCE_FACT.TECHNICAL_DESCRIPTOR_KEY = dbo.TECHNICAL_DESCRIPTOR.TECHNICAL_DESCRIPTOR_KEY
	INNER JOIN dbo.DATE_TIME ON dbo.INTERACTION_RESOURCE_FACT.START_DATE_TIME_KEY = dbo.DATE_TIME.DATE_TIME_KEY
	INNER JOIN dbo.IRF_USER_DATA_CUST_2 ON dbo.INTERACTION_RESOURCE_FACT.INTERACTION_RESOURCE_ID = dbo.IRF_USER_DATA_CUST_2.INTERACTION_RESOURCE_ID
	INNER JOIN dbo.IRF_USER_DATA_KEYS ON dbo.INTERACTION_RESOURCE_FACT.INTERACTION_RESOURCE_ID = dbo.IRF_USER_DATA_KEYS.INTERACTION_RESOURCE_ID
	INNER JOIN dbo.USER_DATA_CUST_DIM_5 ON dbo.IRF_USER_DATA_KEYS.CUSTOM_KEY_5 = dbo.USER_DATA_CUST_DIM_5.ID
	INNER JOIN dbo.INTERACTION_DESCRIPTOR ON dbo.IRF_USER_DATA_KEYS.INTERACTION_DESCRIPTOR_KEY = dbo.INTERACTION_DESCRIPTOR.INTERACTION_DESCRIPTOR_KEY
	INNER JOIN dbo.USER_DATA_CUST_DIM_2 ON dbo.IRF_USER_DATA_KEYS.CUSTOM_KEY_2 = dbo.USER_DATA_CUST_DIM_2.ID
	INNER JOIN dbo.USER_DATA_CUST_DIM_1 ON dbo.IRF_USER_DATA_KEYS.CUSTOM_KEY_1 = dbo.USER_DATA_CUST_DIM_1.ID
	INNER JOIN dbo.IRF_USER_DATA_CUST_1 ON dbo.INTERACTION_RESOURCE_FACT.INTERACTION_RESOURCE_ID = dbo.IRF_USER_DATA_CUST_1.INTERACTION_RESOURCE_ID
	INNER JOIN dbo.USER_DATA_CUST_DIM_7 ON dbo.IRF_USER_DATA_KEYS.CUSTOM_KEY_7 = dbo.USER_DATA_CUST_DIM_7.ID
	INNER JOIN dbo.USER_DATA_CUST_DIM_5 AS USER_DATA_CUST_DIM_5_1 ON dbo.USER_DATA_CUST_DIM_5.ID = USER_DATA_CUST_DIM_5_1.ID
	INNER JOIN dbo.USER_DATA_CUST_DIM_4 ON dbo.IRF_USER_DATA_KEYS.CUSTOM_KEY_4 = dbo.USER_DATA_CUST_DIM_4.ID
	INNER JOIN dbo.IRF_USER_DATA_CUST_3 ON dbo.INTERACTION_RESOURCE_FACT.INTERACTION_RESOURCE_ID = dbo.IRF_USER_DATA_CUST_3.INTERACTION_RESOURCE_ID
	INNER JOIN dbo.USER_DATA_CUST_DIM_3 ON dbo.IRF_USER_DATA_KEYS.CUSTOM_KEY_3 = dbo.USER_DATA_CUST_DIM_3.ID


WHERE (1=1)
	And MEDIA_TYPE.MEDIA_NAME = 'Voice' -- IVR Calls (not email or chat)
	And DATE_TIME.LABEL_YYYY_MM_DD between '2018-10-12' and '2018-10-12' -- Includes calls starting on first value and second value
	--And [LABEL_HH24] between 16 and 16 -- Between specific hours, 24 hour designation, Central Time Zone.
	--And CONVERT(VARCHAR(8), DATEADD(HOUR, - 5, DATEADD(S, dbo.INTERACTION_RESOURCE_FACT.START_TS, '1970-01-01')), 114) between '16:00:00' and '16:05:00' -- Between specific times (Central Time Zone).
	--And CONVERT(VARCHAR(8), DATEADD(hh, -5, INTERACTION_RESOURCE_FACT.START_TS), 114) between '16:00:00' and '23:59:59' -- Timeframe (Central Time)
	--And INTERACTION_FACT.SOURCE_ADDRESS in ('36095409355') -- ANI Filter
	--And INTERACTION_FACT.INTERACTION_ID = ''
	--And INTERACTION_FACT.MEDIA_SERVER_IXN_ID = ''
	--And INTERACTION_FACT.MEDIA_SERVER_IXN_GUID = ''
	--And IRF_USER_DATA_CUST_1.CUSTOM_DATA_3 like '%00413438678%' -- Member ID
	--And IRF_USER_DATA_CUST_1.CUSTOM_DATA_5 = '19720913' -- Member DOB
	--And IRF_USER_DATA_CUST_1.CUSTOM_DATA_8 = '98512' -- Member Zip Code
	--And IRF_USER_DATA_CUST_1.CUSTOM_DATA_6 like '%John%' -- Member First Name
    --And IRF_USER_DATA_CUST_1.CUSTOM_DATA_7 like '%Smith%' -- Member Last Name
	--And IRF_USER_DATA_CUST_1.CUSTOM_DATA_4 Not in ('0000000') -- Policy Number
	--And USER_DATA_CUST_DIM_1.DIM_ATTRIBUTE_4 = 'English' -- Language
	--And  IRF_USER_DATA_CUST_1.CUSTOM_DATA_1 in ('8442347916') -- Dialed Number
	And USER_DATA_CUST_DIM_2.DIM_ATTRIBUTE_1 = 'Simplified' -- IVR Product (Simplfied, Vision, Dental, PacifiCare)
	--And USER_DATA_CUST_DIM_2.DIM_ATTRIBUTE_3 = 'UHC' -- Unit (UHC, OPT) 
    And USER_DATA_CUST_DIM_2.DIM_ATTRIBUTE_4 in ('EI','MR') -- Business Segment (EI,MR,CS,SpecBen,AARPHealth,OptumTech)
	--And IRF_USER_DATA_CUST_3.CUSTOM_DATA_7 ='E01' -- BIE code (ENT_CampaignCD)
	--And IRF_USER_DATA_CUST_3.CUSTOM_DATA_8 ='SNI' -- Program Code (ENT_ProgramCD)
	--And USER_DATA_CUST_DIM_5_1.DIM_ATTRIBUTE_1 = 'Y' -- Survey Flag in Genesys (not Legacy)
	--And IRF_USER_DATA_CUST_1.CUSTOM_DATA_16 = '00086453361539031854' -- UCID
	--And INTERACTION_FACT.TARGET_ADDRESS = ''
	--And RESOURCE_.EMPLOYEE_ID = 'Agent Employee ID'
	--And IRF_USER_DATA_CUST_2.CUSTOM_DATA_3 = '<VQ Name>'

GROUP BY
	dbo.INTERACTION_FACT.INTERACTION_ID,
	dbo.MEDIA_TYPE.MEDIA_NAME,
	dbo.INTERACTION_RESOURCE_FACT.START_TS, 
    dbo.INTERACTION_RESOURCE_FACT.END_TS,
	dbo.INTERACTION_FACT.SOURCE_ADDRESS,
	dbo.INTERACTION_FACT.TARGET_ADDRESS, 
    dbo.INTERACTION_TYPE.INTERACTION_TYPE,
	dbo.INTERACTION_RESOURCE_FACT.INTERACTION_RESOURCE_ORDINAL,
	dbo.RESOURCE_.RESOURCE_NAME, 
    dbo.RESOURCE_.AGENT_NAME,
	dbo.RESOURCE_.EMPLOYEE_ID,
	dbo.RESOURCE_.RESOURCE_TYPE,
	dbo.USER_DATA_CUST_DIM_5.DIM_ATTRIBUTE_4, 
    dbo.IRF_USER_DATA_CUST_2.CUSTOM_DATA_11,
	dbo.IRF_USER_DATA_CUST_2.CUSTOM_DATA_3,
	dbo.TECHNICAL_DESCRIPTOR.TECHNICAL_RESULT, 
    dbo.TECHNICAL_DESCRIPTOR.RESOURCE_ROLE,
	dbo.INTERACTION_DESCRIPTOR.CUSTOMER_SEGMENT,
	dbo.INTERACTION_DESCRIPTOR.SERVICE_TYPE, 
    dbo.INTERACTION_DESCRIPTOR.SERVICE_SUBTYPE,
	dbo.INTERACTION_DESCRIPTOR.BUSINESS_RESULT,
	dbo.USER_DATA_CUST_DIM_5.DIM_ATTRIBUTE_2, 
    dbo.USER_DATA_CUST_DIM_1.DIM_ATTRIBUTE_1,
	dbo.USER_DATA_CUST_DIM_4.DIM_ATTRIBUTE_2,
	dbo.USER_DATA_CUST_DIM_1.DIM_ATTRIBUTE_2,
	dbo.USER_DATA_CUST_DIM_1.DIM_ATTRIBUTE_3, 
    dbo.USER_DATA_CUST_DIM_1.DIM_ATTRIBUTE_4,
	dbo.USER_DATA_CUST_DIM_1.DIM_ATTRIBUTE_5,
	dbo.USER_DATA_CUST_DIM_2.DIM_ATTRIBUTE_1, 
    dbo.USER_DATA_CUST_DIM_2.DIM_ATTRIBUTE_2,
	dbo.USER_DATA_CUST_DIM_2.DIM_ATTRIBUTE_3,
	dbo.USER_DATA_CUST_DIM_2.DIM_ATTRIBUTE_4, 
    dbo.USER_DATA_CUST_DIM_2.DIM_ATTRIBUTE_5,
	dbo.IRF_USER_DATA_CUST_1.CUSTOM_DATA_3,
	dbo.IRF_USER_DATA_CUST_1.CUSTOM_DATA_4, 
    dbo.IRF_USER_DATA_CUST_1.CUSTOM_DATA_5,
	USER_DATA_CUST_DIM_5_1.DIM_ATTRIBUTE_1,
	dbo.IRF_USER_DATA_CUST_1.CUSTOM_DATA_6, 
    dbo.IRF_USER_DATA_CUST_1.CUSTOM_DATA_7,
	dbo.IRF_USER_DATA_CUST_1.CUSTOM_DATA_8,
	dbo.IRF_USER_DATA_CUST_2.CUSTOM_DATA_1, 
    dbo.IRF_USER_DATA_CUST_1.CUSTOM_DATA_1,
	dbo.INTERACTION_FACT.MEDIA_SERVER_IXN_ID,
	dbo.INTERACTION_FACT.MEDIA_SERVER_IXN_GUID,
	dbo.IRF_USER_DATA_CUST_1.CUSTOM_DATA_16,
    dbo.IRF_USER_DATA_CUST_3.CUSTOM_DATA_6,
	dbo.IRF_USER_DATA_CUST_3.CUSTOM_DATA_7,
	dbo.IRF_USER_DATA_CUST_3.CUSTOM_DATA_8

Order By
	DATEADD(HOUR, - 5, DATEADD(S, dbo.INTERACTION_RESOURCE_FACT.START_TS, '1970-01-01')) desc, dbo.INTERACTION_FACT.INTERACTION_ID desc, dbo.INTERACTION_RESOURCE_FACT.INTERACTION_RESOURCE_ORDINAL desc
